language: java

jdk:
  - oraclejdk8

env:
  global:
    secure: PZMaluaHnK4BGfl3VnQADn/ZAj9NNLIsjcT/IpDrpOPBQO/5B7yWHYg3ckuBvWl4vFfOUTznOI5p63jMaIRlNfAbZrTEW0HzEtPhYY5PtjsL/nH2z+QXb/WBshJoCeuB7l/iYd0tZXMIVHMq4i51HMNIf3Gr/uchleLoTdN95Yoa9dyKblUxgfZG9sRqeXwVHjcHbgvIljwTHbc0656GDtO04AotomJpGgUjHixzgobKV1P937UDu0VoWa8PLthtVw3FxIx2e9PodnfQPJ7u2FbK+a1pqK6Yk3bVMGW3qu4YJHoiFKw0R3G6pzicphp8PP+8wnUSA8oRERS4nE35sJbsO3LSnUA+ydqmjT6wRBgi4V5PCVfWKfxjQ+jo12orV0xEd648YLhixb+X3k7C6FYQ1gX4j+zVgy2L+ZVkwPTGnjoK61IadI5FG50s8F3SXujSnGgLptnGloYQx9gk5+RHaFqWYPhhMGD+0KPJ4GoFlZBQDuhW7H/I2ibYBG7YJGV70txvqjMETAab3E7RRm2M/WfiyvjUGVRanQkm/jPqG12wjVmHthUbbCX1GR5DPBHr8WbDSsZJNYeJUDNSgqWkVjE9DGZmgsRXsIqwjKWALek40htJ3+1bACvDHVqEoXWXOpDDVE0ZF/uLcdCelGhdK/iIOuNg8x6RvN/SHfc=
script: "mvn cobertura:cobertura"

after_success:
  - bash <(curl -s https://codecov.io/bash) -t $CODECOV_TOKEN

