language: java

jdk:
  - oraclejdk8

env:
  global:
    secure: PeCDJIVVKIB8OCvrJwktp8H1eV64oCJPkEximhmbSXRGaJ4Ut8vvyd6Tk403UoBvgyHiGXGQr2+pH0VI5+BCQ5uKy38YI3gWxU5hxObedlztAQO6CqVxhCRiNe1gx2JT36iWwstW/HQnCKEPJrLG9E8Yo2QYZVv3+7CjSJ7ZtL/zcRkgWf2JHw47W0sGXDoK50w7jMnyz9rxu/UyqSpzqg5BC20DgWPpv4VDtmINH7swbo0rc5UAk7eNGg4kcTKQFV7HIjCLyN+LYs5sX9op/US7ufOIk+yEV0WjmlT/W5hvZMCQ4YDVInih+3pdGF1hHvRtvp3oycsBLHP+kSJEYC/m4kd3/Tym3btKpvgTl2vnylcKLatCejVuDoL08TIVzfwZIHK6c4RZxasiadvgXALLJozAwTYBvQQWPIpTeU2wAevJm/KIX4LHVyeNCXR1hDYGSdP2t7/faHSCZTehSbyAz6pajpfcl8ZwiVb/vC1/5lXJWtpH1YiTFBZlJE9eWIJe3qI9hm+QLbmj7S0XcXqlXuID4vwpMsyGnAQsxUcFRetsLkXcsAp0R4oGCi+4tbyT7ZFz5TfKktXs1fIpwMWASmctYiOKrtwOY4Lbu5bcZriprsSswNpkTIztMVGZNtIyJdlDnDOeYHAMrckg6fr9ZvcekaRgKPhxYqWXws8=
script: "mvn cobertura:cobertura"

after_success:
  - bash <(curl -s https://codecov.io/bash) -t $CODECOV_TOKEN

